apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-service
spec:
  selector:
    matchLabels:
      run: rabbitmq-service
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq-service
    spec:
      hostname: my-rabbit
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 20
          tcpSocket:
            port: 5672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    run: rabbitmq-service
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    run: rabbitmq-service
