apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  selector:
    matchLabels:
      run: frontend-service
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: dubersfeld/frontend-server
        imagePullPolicy: IfNotPresent
        readinessProbe:
          periodSeconds: 30
          tcpSocket:
            port: 8080
        env:
        - name: GUTENBERG_CONFIG_URI
          value: "http://config-service:8888"
        - name: PROFILE
          value: dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: frontend-service
