apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      run: user-service
  replicas: 1
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
      - name: user-service
        image: dubersfeld/user-server
        imagePullPolicy: IfNotPresent
        readinessProbe:
          periodSeconds: 30
          tcpSocket:
            #path: /userByName
            port: 8084
        env:
        - name: GUTENBERG_CONFIG_URI
          value: "http://config-service:8888"
        - name: PROFILE
          value: dev
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    run: user-service
spec:
  ports:
  - port: 8084
    protocol: TCP
  selector:
    run: user-service
