apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  selector:
    matchLabels:
      run: review-service
  replicas: 1
  template:
    metadata:
      labels:
        run: review-service
    spec:
      containers:
      - name: review-service
        image: dubersfeld/review-server
        readinessProbe:
          periodSeconds: 30
          tcpSocket:
            port: 8082
        env:
        - name: GUTENBERG_CONFIG_URI
          value: "http://config-service:8888"
        - name: PROFILE
          value: dev
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  labels:
    run: review-service
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    run: review-service
