apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      run: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: dubersfeld/eureka-server 
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    run: eureka-service
spec:
  ports:
  - port: 8761
    protocol: TCP
  selector:
    run: eureka-service
