#server:
#  port: 8083
#  servlet:
#    context-path:

#spring:
#  data:
#    mongodb:
#      uri: mongodb://spring:password1234@localhost:27017/booksonline
          
          
# base server URLs
#baseBooksUrl: http://localhost:5555/books 
    