server:
  port: 9090
  servlet:
    context-path: /admin
    
spring:
  data:
    mongodb:
      uri: mongodb://spring:password1234@books-mongodb:27017/booksonline
    
  cloud:
    stream:
      bindings:
        output:
          destination: bookChangeTopic
          content-type: application/json
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq-service
                port: 5672
                username: spring
                password: password1234
                virtual-host: /
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
