server:
  port: 8083
  servlet:
    context-path:

spring:
  data:
    mongodb:
      uri: mongodb://spring:password1234@books-mongodb:27017/booksonline
          

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
     
     
# base server URLs
baseBooksUrl: http://book-service:8081 
    


