server:
  port: 8084
  servlet:
    context-path:
    
spring:
  data:
    mongodb:
      #uri: mongodb://spring:password1234@localhost:27017/booksonline
      uri: mongodb://spring:password1234@books-mongodb:27017/booksonline
    
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
